# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 139be28b39abeb5719f1bad931143b6b5f8a8eead0a1895d96927d6f52cc8def9399d0631371ea26b6e28b96f0820f379ea04255dda7a240ff1fe07f2048675f

test:
  secret_key_base: 356cd4489ba1de329d907ced3eb74cdf21344290d7e409dc5c211f8abd00a4cae73ce4f0d73676e36e89d1eeaf976169e5813c18d6d75b926d23f20aac8bed63

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
